name: Create PDF from Markdowwn
description: |
  Creates a PDF file from the given markdown input,
  using UnquietCode/martek to generate and render
  LaTeX into a PDF document.

inputs:
  content:
    description: UTF-8 encoded markdown string
    required: false
  content64:
    description: Base64 encoded UTF-8 markdown string
    required: false
  contentURL:
    description: a public URL where markdown content can be downloaded
    required: false
outputs:
  pdf:
    description: rendered PDF file, base64 encoded 
runs:
  using: docker
  image: docker://ghcr.io/unquietcode/martek_create-pdf-action:latest
  args:
    - "${{ inputs.content }}"
    - "${{ inputs.content64 }}"
    - "${{ inputs.contentURL }}"
branding:
  icon: git-commit
  color: gray-dark
